# Generated by Django 5.2.1 on 2025-05-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='sublinea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.sublineaarticulo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='core.rol'),
        ),
    ]
