# Generated by Django 5.2.1 on 2025-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'ordering': ['valor_minimo'], 'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        # migrations.AddField(
        #     model_name='descuento',
        #     name='valor_maximo',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='descuento',
        #     name='valor_minimo',
        #     field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        # ),
        migrations.AlterField(
            model_name='descuento',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo_condicion',
            field=models.CharField(choices=[('monto', 'Precios'), ('cantidad', 'Cantidad')], max_length=10),
        ),
    ]
