# Generated by Django 5.2.1 on 2025-05-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cliente_nombre_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='core.rol'),
            preserve_default=False,
        ),
    ]
