# Generated by Django 5.2.1 on 2025-05-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promocionproducto_cantidad_max_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocionproducto',
            unique_together=set(),
        ),
    ]
