# Generated by Django 5.2.1 on 2025-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_promocionproducto_unique_together'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='promocion',
        #     name='grupo_proveedor_id',
        #     field=models.UUIDField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='promocion',
        #     name='linea_articulo_id',
        #     field=models.UUIDField(blank=True, null=True),
        # ),
    ]
