# Generated by Django 5.2.1 on 2025-05-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promocion_grupo_proveedor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionProducto',
            fields=[
                ('verificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='core.articulo')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='core.promocion')),
            ],
            options={
                'db_table': 'verificacion_productos',
            },
        ),
    ]
