# Generated by Django 5.2.1 on 2025-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_promocion_tipo_beneficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='tipo_condicion',
            field=models.CharField(blank=True, choices=[('monto', 'Intervalos de Precios'), ('cantidad', 'Intervalos de Cantidad')], max_length=10, null=True),
        ),
    ]
