# Generated by Django 5.2.1 on 2025-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_promocion_tipo_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='escalable',
            field=models.BooleanField(default=False, help_text='Si está marcado, la promoción se aplica múltiples veces según cantidad/monto (Casos 1 y 2)'),
        ),
    ]
