# Generated by Django 5.2.1 on 2025-05-27 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_promocion_escalable'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='beneficio_configurado_en_condiciones',
            field=models.BooleanField(default=False, help_text='Indica si el beneficio ya se configuró en las condiciones (evita duplicación)'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='es_promocion_combinada_por_monto',
            field=models.BooleanField(default=False, help_text='Indica si es una promoción del Caso 9 (bonificación + descuento por intervalos)'),
        ),
        migrations.CreateModel(
            name='BonificacionPorIntervalo',
            fields=[
                ('bonificacion_intervalo_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_minimo', models.DecimalField(decimal_places=2, help_text='Monto mínimo para esta bonificación específica', max_digits=10)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo para esta bonificación específica. NULL = sin límite', max_digits=10, null=True)),
                ('bonificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos_monto', to='core.bonificacion')),
            ],
            options={
                'verbose_name': 'Bonificación por Intervalo de Monto',
                'verbose_name_plural': 'Bonificaciones por Intervalos de Monto',
                'db_table': 'bonificaciones_por_intervalo',
                'ordering': ['valor_minimo'],
            },
        ),
    ]
