# Generated by Django 5.2.1 on 2025-05-28 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_promocion_beneficio_configurado_en_condiciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonificacionporintervalo',
            name='bonificacion',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='promocion',
        ),
        migrations.AlterUniqueTogether(
            name='promocionlinea',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promocionlinea',
            name='linea_articulo',
        ),
        migrations.RemoveField(
            model_name='promocionlinea',
            name='promocion',
        ),
        migrations.RemoveField(
            model_name='promocionproducto',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='promocionproducto',
            name='promocion',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='tipo_beneficio',
        ),
        migrations.RenameField(
            model_name='promocion',
            old_name='nombre',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='beneficio_configurado_en_condiciones',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='cantidad_minima',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='es_promocion_combinada_por_monto',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='tipo_condicion',
        ),
        migrations.AlterField(
            model_name='promocion',
            name='canal_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='promociones', to='core.canalcliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocion',
            name='escalable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='promociones', to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('beneficio_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_beneficio', models.CharField(choices=[('bonificacion', 'Solo Bonificación'), ('descuento', 'Solo Descuento'), ('ambos', 'Bonificación + Descuento')], max_length=20)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.promocion')),
            ],
            options={
                'db_table': 'beneficio',
            },
        ),
        migrations.CreateModel(
            name='ProductosBeneficios',
            fields=[
                ('pro_bene_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.articulo')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.beneficio')),
            ],
            options={
                'db_table': 'productos_beneficios',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('rango_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_rango', models.CharField(choices=[('monto', 'Intervalos de Precios'), ('cantidad', 'Intervalos de Cantidad')], max_length=10)),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='core.promocion')),
            ],
            options={
                'db_table': 'rangos',
                'ordering': ['minimo'],
            },
        ),
        migrations.CreateModel(
            name='ProductoBonificadoRango',
            fields=[
                ('pro_boni_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones_rango', to='core.articulo')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_bonificados', to='core.rango')),
            ],
            options={
                'db_table': 'producto_bonificado_rangos',
            },
        ),
        migrations.DeleteModel(
            name='Bonificacion',
        ),
        migrations.DeleteModel(
            name='BonificacionPorIntervalo',
        ),
        migrations.DeleteModel(
            name='Descuento',
        ),
        migrations.DeleteModel(
            name='PromocionLinea',
        ),
        migrations.DeleteModel(
            name='PromocionProducto',
        ),
        migrations.DeleteModel(
            name='TipoBeneficio',
        ),
    ]
