# Generated by Django 5.2.1 on 2025-05-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_bonificacionporintervalo_bonificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='cantidad_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
